[BUGFIX] Resolve new placeholders without t3ver_oid
TYPO3/testing-framework pull request #200
Opened 2020-09-10 08:44 UTC by bmack

When removing the t3ver_state=1 (planned for TYPO3 v11)
placeholders which are only there to ease the pain
when publishing, the versioned record and the live record
are in fact the same, which should be covered by
the testing framework

2020-10-06 23:46 UTC, simonschaufi requested changes

2020-10-06 23:46 UTC, simonschaufi commented on Classes/Core/Functional/Framework/DataHandling/ActionService.php
> +        } else {
change `return (int)$row['uid'];` in the line above and leave out the else.

2020-10-13 09:29 UTC, lolli42 requested changes

2020-10-13 09:29 UTC, lolli42 commented on Classes/Core/Functional/Framework/DataHandling/ActionService.php
> +                    'uid',
this does not make sense: select('uid') -> where ('uid' = $liveuid) ???

2020-10-13 09:29 UTC, lolli42 commented on Classes/Core/Functional/Framework/DataHandling/ActionService.php
> +                    $queryBuilder->createNamedParameter(VersionState::NEW_PLACEHOLDER_VERSION, \PDO::PARAM_INT)
does not make sense either: t3ver_state=-1 records always have t3ver_oid != 0

2020-10-13 10:54 UTC, lolli42 approved these changes

2020-10-13 10:55 UTC, lolli42 commented
Actually, this is fine with the pending removal placeholder change in v11

2020-10-13 10:55 UTC, merged