Fix PHP 8.1 compatibility.
TYPO3/testing-framework pull request #276
Opened 2021-09-09 17:24 UTC by Crell

### Changes proposed in this pull request

Since PHP 8.1, it's no longer possible to pass `$GLOBALS` by reference.  cf: https://wiki.php.net/rfc/restrict_globals_usage

The functional tests, however, do that on every single subrequest, which causes... a few thousand failures.  Fortunately there's an easy workaround.

(I'm not certain if this fixes all PHP 8.1 issues, but it is certainly the lion's share of them that can be found so far.)

Fixes: #

2021-09-09 17:29 UTC, oliverklee approved these changes

2021-09-09 18:28 UTC, sbuerk approved these changes
Currently not seeing if it could have a sideeffekt.
For now it reduces a majorty core functional errors for php8.1, and also reduce the memory usages which rised for 8.1, not to that level of <8.1.

```
sysext:core   987 MB to 609 MB   on 8.1  | no change for 8.0
complete      4.68 GB => 1.54 GB on 8.1  | no change for 8.0
```

2021-09-09 18:52 UTC, oliverklee approved these changes

2021-09-10 08:55 UTC, sbuerk requested changes
Sry Larry, may you to your PR a second replacement / fix ? Generally the same thing, but in another place.

Classes/Core/Functional/Framework/Frontend/RequestBootstrap
Line: 173 - 176

```php
ArrayUtility::mergeRecursiveWithOverrule(
    $GLOBALS,
    $this->context->getGlobalSettings() ?? []
);
```

with

```php
$override = $this->context->getGlobalSettings() ?? [];
foreach ($GLOBALS as $k => $v) {
    if (isset($override[$k])) {
        ArrayUtility::mergeRecursiveWithOverrule($GLOBALS[$k], $override[$k]);
    }
}
```

Both places together would reduce the functional error count for php81 to 17 (mariadb).

```
Tests: 4739, Assertions: 38070, Failures: 17, Skipped: 22, Incomplete: 7.
```

2021-09-10 11:11 UTC, lolli42 commented
@sbuerk Let's take care of the executeFrontendRequest() related thing with a dedicated patch.
I'll merge the initial patch from Larry as is.

2021-09-10 11:14 UTC, merged